spring:
  mail:
    host: smtp.gmail.com
    username: kheliltassnime@gmail.com
    password: rdumizgelhcfeywr
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    auth: true